{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: module-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "module-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "module-service.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
